# Allows repositories in shopware organization read access to apps & services terraform modules

issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:shopware/.*
claim_pattern:
  workflow_ref: shopware/.*/.github/workflows/.*

permissions:
  contents: read

repositories:
  - terraform-app-hosting-infra-modules
  - terraform-app-hosting-ecs-module
  - terraform-app-hosting-static-web-module
  - services-aws-tags-module
  - services-aws-cloudfront-s3-module
