# Allows repositories in shopware organization read access to app-sdk-go repository

issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:shopware/.*

permissions:
  contents: read

repositories:
  - app-sdk-go
