# Allows shopware/shopware to read collaborators

issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:shopware/.*:.*
claim_pattern:
  workflow_ref: shopware/.*

permissions:
  pull_requests: read
  issues: read
  organization_projects: write
  repository_projects: write

repositories:
  - shopware
  - shopware-private
