# Allows shopware/store-api-reference and shopware/admin-api-reference to pull its required components

issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:shopware/*-api-reference:.*
claim_pattern:
  workflow_ref: shopware/*-api-reference/.github/workflows/(manual_versioning|scheduled_versioning)\.yml@.*
permissions:
  contents: read

repositories:
  - SwagCommercial
  - SwagCustomizedProducts
  - swagdigitalsalesrooms
