issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:shopware/partner-git-access:.*
claim_pattern:
  workflow_ref: shopware/partner-git-access/.github/workflows/(cron|test).ya?ml@.*

permissions:
  contents: read
  metadata: read
  # required for PR sync in the future
  # contents: write
  # actions: write
  # workflows: write

# allow all repos
repositories: []
