issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:shopware/saas:.*
claim_pattern:
  workflow_ref: shopware/saas/.github/workflows/preview-environment.yml@.*

permissions:
  pull_requests: write

# Allow access to all repositories of the shopware organization
repositories: []
