issuer: https://token.actions.githubusercontent.com
subject: repo:shopware-redstone/cluster-infrastructure:.*

permissions:
  contents: read
  packages: read

repositories:
  - paas-backend
  - fastly-operator
  - shopware-operator
