issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:shopware/shopware:.*
claim_pattern:
  workflow_ref: shopware/shopware/.github/workflows/.*

permissions:
  metadata: read
  members: read
  pull_requests: write

# Allow access to all repositories of the shopware organization
repositories: []
