issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:shopware/saas:.*
claim_pattern:
  workflow_ref: shopware/saas/.github/workflows/backport.ya?ml.*
permissions:
  contents: write
  pull_requests: write
  workflows: write

repositories:
  - saas
