# Allows the product-operations-dd-monitoring repository to request tokens to read contents of all SaaS-related repositories.

issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:shopware/product-operations-dd-monitoring:.*

permissions:
  contents: read

repositories:
  - saas
  - shopware
  - shopware-private
  - Rufus
  - SwagCommercial
  - SwagDynamicAccess
  - SwagPublisher
  - SwagCmsExtensions
  - SwagCustomizedProducts
  - SwagMigrationAssistant
  - SwagLanguagePack
  - SwagPayPal
  - SwagSocialShopping
  - swagdigitalsalesrooms
  - shopware-configurable-listing-filters
