# Allows shopware/shopware to push to shopware/shopware-private to keep them in sync

issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:shopware/shopware:ref:refs/heads/(trunk|6.5.x)
claim_pattern:
  workflow_ref: shopware/shopware/.github/workflows/sync.ya?ml@refs/heads/(trunk|6.5.x)

permissions:
  contents: write
  actions: write
  workflows: write

repositories:
  - shopware-private
