issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:shopware/shopware(-private)?:.*
claim_pattern:
  workflow_ref: shopware/shopware(-private)?/.github/workflows/(downstream|nightly|merge-downstreams).ya?ml@.*

permissions:
  actions: write
  contents: read
  pull_requests: write

repositories:
  - SwagCommercial
  - Rufus
