# Allows Shopware Learning Environments in Community Hub be pre-installed with selected premium extensions

issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:shopware/academy-shopdev-plugin:.*
claim_pattern:
  workflow_ref: shopware/academy-shopdev-plugin/.github/workflows/create-template.yml@.*
permissions:
  contents: read

repositories:
  - SwagCommercial
  - SwagCustomizedProducts
  - SwagPayPal
  - SwagSocialShopping
  - swagdigitalsalesrooms
