# Allows gh-project-automation to cancel stuck workflows

issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:shopware/gh-project-automation:ref:refs/heads/main
claim_pattern:
  workflow_ref: shopware/gh-project-automation/.github/workflows/cancel-stuck-workflows.yml@refs/heads/main

permissions:
  actions: write

repositories:
  - SwagCommercial
  - Rufus
